export const PROJECT_NAME_MAX_LENGTH = 120;
export const PROJECT_DESCRIPTION_MAX_LENGTH = 50_000;
export const PROJECT_PRIORITY_MAX = 5;
export const PROJECT_SETTING_KEY_MAX_LENGTH = 80;
export const PROJECT_SETTING_VALUE_MAX_LENGTH = 200;

export const TODO_TITLE_MAX_LENGTH = 180;
export const TODO_NOTE_MAX_LENGTH = 50_000;
export const TODO_SORT_ORDER_MAX_LENGTH = 64;
export const TODO_LABEL_NAME_MAX_LENGTH = 40;
export const INSIGHT_PROMPT_MAX_LENGTH = 1200;

export const WORK_LOG_TITLE_MAX_LENGTH = 180;
export const WORK_LOG_DETAIL_MAX_LENGTH = 100_000;

export const API_TOKEN_NAME_MAX_LENGTH = 64;
